package edu.isu.reu.keyboard_one_shot;

import android.content.Intent;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;

public class StringAuthenticationActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_string_authentication);

        // get the intent string
        String authentication_string = get_intent_string();

        // display the intent string
        display_intent_string(authentication_string);

        // display the keyboard
        display_keyboard();

        // display the results of the authentication
        display_authentication_results();

        // close the activity
        finish();
    }

    /**
     * get the authentication string from the intent
     */
    private String get_intent_string(){
        Intent intent = getIntent();

        return intent.getStringExtra(MainActivity.AUTHENTICATION_STRING);
    }

    /**
     * display the string in the text_to_type_textbox
     */
    private void display_intent_string(String text){
        //TODO
    }

    private void display_keyboard(){
        // display text which has been entered into the keyboard
        // also display what the user should be typing
        // e.x. bold the next letter to be typed
        //TODO

        // determine when the user has finished entering the string
        //TODO

        // return when typing has finished
        //TODO
    }

    /**
     * this method creates an intent to another activity
     *
     * this other activity will
     * compute the result of the authentication
     *
     * display the results of the authentication
     */
    private void display_authentication_results(){
        // create intent for display activity
        //TODO

        // put extra string generated by keyboard data
        //TODO

        // start the display activity
        //TODO
    }
}
